{% set version = "1.1.1" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/InfOmics/CRISPRitz/archive/v{{ version }}.tar.gz
  sha256: a49ba9a17d25f88632fef5837a0e195d866a87cc50f3952aa189306d577812fa

build:
  number: 1

requirements:
  build:
    - {{compiler('cxx')}} =5.4 # [not osx]
    - {{compiler('cxx')}} # [osx]

  host:
    - make
    - boost
    - openmp
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftoolsf
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - libcxxabi
    - python
    
  run:
    - make
    - boost
    - openmp
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftoolsf
    - boost
    - tk
    - openmp
    - libdeflate
    - libcxx
    - libcxxabi
    - python
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/InfOmics/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
