# Do not forget to update the version string in the searchgui.py file
{% set name = "SearchGUI" %}
{% set version = "4.0.0" %}

package:
  name: searchgui
  version: {{ version }}

build:
  number: 0
  #noarch: generic

source:
  url: http://genesis.ugent.be/maven2/eu/isas/searchgui/{{ name }}/{{ version }}/{{ name }}-{{ version }}-mac_and_linux.tar.gz
  sha256: 81be419765913e9f870559976a9adb9f316ffa5ce6f900f453eccb77986dfe2c

requirements:
  build:
    - {{ compiler('c') }}
  run:
    - openjdk >=11
    - mono >=4.0.0
    - python
    - dotnet

test:
  commands:
    - searchgui eu.isas.searchgui.cmd.FastaCLI
    - searchgui eu.isas.searchgui.cmd.FastaCLI -Xms512m -Xmx1g

about:
  home: https://github.com/compomics/searchgui
  license: Apache License 2.0
  license_family: APACHE
  summary: User-friendly graphical tool for using proteomics identification search engines
  description: |
    SearchGUI is a user-friendly open-source graphical user interface for configuring and running proteomics identification search engines, currently supporting X!Tandem, MS-GF+, MS Amanda, MetaMorpheus, MyriMatch, Comet, Tide, Andromeda and OMSSA.


extra:
  notes: |
    SearchGUI is Java program that comes with a custom wrapper shell script.
    This shell wrapper is called "opsin" and is on $PATH by default. By default
    "-Xms512m -Xmx1g" is set in the wrapper. If you want to overwrite it you can
    specify these values directly after your binaries. If you have _JAVA_OPTIONS
    set globally this will take precedence.
    For example run it with "searchgui -Xms512m -Xmx1g"
  identifiers:
    - biotools:searchgui
    - usegalaxy-eu:search_gui
    - doi:10.1002/pmic.201000595
